---

- name: Provision MRPS server and clients
  hosts: mrps
  remote_user: root
  roles:
    - role: erlang
    - role: prometheus
      prometheus_platform_architecture: linux-armv7
      prometheus_install: false
      prometheus_node_exporter_install: true
      prometheus_alert_manager_install: false


- name: Install MRPS release
  hosts: server
  remote_user: root

  roles:
  - role: git
  - role: mrps
  tags: install-release


- name: Install Tsung on clients
  hosts: clients
  remote_user: root
  tasks:
    - name: install tsung
      apt: 
        name: tsung
        state: latest

    # https://github.com/processone/tsung/issues/276
    - name: create symlinks
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        follow: no
        state: link
      with_items:
        - { src: '/usr/share', dest: '/usr/lib/share' }
        - { src: '/usr/lib/arm-linux-gnueabihf/tsung', dest: '/usr/lib/tsung' }

    - name: copy tsung spec
      template:
        src: templates/tsung.xml.j2
        dest: "~/client/tsung.xml"
      vars:
        server: "{{ groups['server'][0] }}"


- name: Setup monitoring system
  import_playbook: monitor.yml
