---
- name: Provision MRPS server and clients
  hosts: mrps
  remote_user: root
  roles:
    - role: git
    - role: erlang
    - role: prometheus
      prometheus_platform_architecture: linux-armv7
      prometheus_install: false
      prometheus_node_exporter_install: true
      prometheus_alert_manager_install: false

  tasks:
    - name: clone mrps repo
      git:
        repo: https://github.com/lambdaclass/million_requests_per_second.git
        dest: million_requests_per_second
        force: yes


- name: Install Tsung on clients
  hosts: clients
  remote_user: root
  roles:
    - tsung

  tasks:
    - name: copy prometheus config
      template:
        src: templates/tsung.xml.j2
        dest: "~/million_requests_per_second/tsung.xml"
      vars:
        server: "{{ groups['server'][0] }}"


# - name: Setup monitoring system
#   import_playbook: monitor.yml
