---
- name: "(Install: All OSs) Install NGINX Open Source RTMP Module"
  package:
    name: nginx-module-rtmp
    state: present
  when: nginx_type == "opensource"

- name: "(Install: All OSs) Install NGINX Plus RTMP Module"
  package:
    name: nginx-plus-module-rtmp
    state: present
  when: nginx_type == "plus"

- name: "(Setup: All NGINX) Load NGINX RTMP Module"
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    line: load_module modules/ngx_rtmp_module.so;
  notify: "(Handler: All OSs) Reload NGINX"
