---
- name: "(Install: All OSs) Install NGINX Open Source JavaScript Module"
  package:
    name: nginx-module-njs
    state: present
  when: nginx_type == "opensource"

- name: "(Install: All OSs) Install NGINX Plus JavaScript Module"
  package:
    name: nginx-plus-module-njs
    state: present
  when: nginx_type == "plus"

- name: "(Setup: All NGINX) Load NGINX JavaScript Module"
  blockinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: BOF
    block: |
      load_module modules/ngx_http_js_module.so;
      load_module modules/ngx_stream_js_module.so;
  notify: "(Handler: All OSs) Reload NGINX"
