---
- name: "(Install: SUSE) Combine NGINX Plus Certificate and License Keys"
  assemble:
    src: /etc/ssl/nginx
    dest: /etc/ssl/nginx/nginx-repo-bundle.crt

- name: "(Install: SUSE) Add NGINX Plus Repository"
  zypper_repository:
    name: nginx-plus
    repo: https://plus-pkgs.nginx.com/sles/12?ssl_clientcert=/etc/ssl/nginx/nginx-repo-bundle.crt&ssl_verify=host
