---
- name: "(Setup: NGINX Plus) Setup NGINX Plus API"
  blockinfile:
    path: "{{ nginx_rest_api_location }}"
    create: yes
    block: |
      server {
          listen {{ nginx_rest_api_port }};
          location /api {
      {% if nginx_rest_api_write %}
              api write=on;
      {% else %}
              api;
      {% endif %}
          }
      {% if nginx_rest_api_dashboard %}
          location = /dashboard.html {
              root /usr/share/nginx/html;
          }
      {% endif %}
      }
  notify: "(Handler: All OSs) Reload NGINX"
