---

- name: check installation
  command: erl -version
  register: erlang_installed
  ignore_errors: true
  changed_when: false

- name: install Erlang
  include: install_erlang.yml
  when: erlang_installed is failed

- name: install erlang extra packages
  apt: name={{ item }} state=present
  with_items: "{{ erlang_extra_packages }}"
